### ISSUE TITLE
Make tab color respect android chrome API

### ISSUE THREAD

**Issue by crutchcorn** [tim-sueberkrueb/material-browser#1]
This would be a great feature to have

**Comment by tim-sueberkrueb** [comment]
@crutchcorn very good idea!
Just for reference: https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android

**Comment by tim-sueberkrueb** [comment]
Done (see https://plus.google.com/+TimS%C3%BCberkr%C3%BCbDE/posts/dpKHbrtB98m).
