### ISSUE TITLE
website

### ISSUE THREAD

**Issue by loctauxphilippe** [tim-sueberkrueb/material-browser#16]
you can create a little website with the branch "gh-pages", that'd be good!
also you could move the translations there so you don't need to get them when you clone the repo :smile:

**Comment by VirusKA** [comment]
kinda unnecessary but I'll work on it.

**Comment by tim-sueberkrueb** [comment]
@VirusKA okay, cool :)

**Comment by VirusKA** [comment]
ok I finished but @tim-sueberkrueb, you need to make a gh-pages branch to merge it

**Comment by tim-sueberkrueb** [comment]
@VirusKA great, created the branch :)

**Comment by VirusKA** [comment]
time to close this one

**Comment by tim-sueberkrueb** [comment]
Yep, thanks very much :)
