### ISSUE TITLE
New tab page

### ISSUE THREAD

**Issue by tim-sueberkrueb** [tim-sueberkrueb/material-browser#9]
* [x] Drag and Drop support
* [x] Update and save model
* [x] Right click on Bookmark to add dashboard item
* [x] Dashboard icon in tab
* [x] Get icon (http://stackoverflow.com/a/22007642)
  * Getting icon via the open source icon finder http://icons.better-idea.org/
* [x] Respect theme color

**Comment by VirusKA** [comment]
i know this isn't _really_ material design, but i really enjoy Microsoft Edge's new tab page and i'll like to see some of it implemented here.

**Comment by crutchcorn** [comment]
I'd really rather prefer to see a material design new tab page rather than following suit with Metro

**Comment by VirusKA** [comment]
I didn't mean a flat out copy of the new tab. I meant the layout.

**Comment by tim-sueberkrueb** [comment]
Development on this goes on here: https://github.com/tim-sueberkrueb/material-browser/tree/feature-9

**Comment by tim-sueberkrueb** [comment]
Just for reference: http://stackoverflow.com/a/22007642
By implementing something like that we can get the icons.

**Comment by tim-sueberkrueb** [comment]
Done :)
